# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 23:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_remove_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(through='events.Attendee', to=settings.AUTH_USER_MODEL),
        ),
    ]
