# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160629_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='timestamp',
        ),
    ]
